stages:
  - unit-test
  - pages

unit-test:
  stage: unit-test
  rules:
  - if: $CI_PIPELINE_SOURCE == "push"
  image: gradle:7.5.0-jdk17
  allow_failure: true
  script:
      - |
        ./gradlew test
        find build/test-results/test/
artifacts:
    reports:
      junit: build/test-results/**/TEST-*.xml
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml

coverage-to-cobertura:
  needs:
    - job: unit-test
      artifacts: true
  stage: unit-test
  image: haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/src/main/java/ > build/reports/coverage.xml
  artifacts:
    reports:
      coverage_report: 
        coverage_format: cobertura
        path: build/reports/coverage.xml

make-javadoc:
  stage: unit-test
  rules:
  - if: $CI_PIPELINE_SOURCE == "push"
  image: gradle:7.5.0-jdk17
  script:
      - |
        ./gradlew javadoc
        cp -r build/docs/javadoc/ public/
artifacts:
    paths:
    - public/

pages:
  needs:
    - job: make-javadoc
      artifacts: true
  rules:
  - if: $CI_PIPELINE_SOURCE == "push"
  image: busybox
  stage: pages
  script:
  - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public/
